USE [master]
GO

/****** Object:  Database [CRTX_Extras]    Script Date: 10/16/2020 ******/
CREATE DATABASE [CRTX_Extras]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CRTX_Extras', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\CRTX_Extras.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CRTX_Extras_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\CRTX_Extras_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [CRTX_Extras] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CRTX_Extras].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CRTX_Extras] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CRTX_Extras] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CRTX_Extras] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CRTX_Extras] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CRTX_Extras] SET ARITHABORT OFF 
GO

ALTER DATABASE [CRTX_Extras] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CRTX_Extras] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CRTX_Extras] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CRTX_Extras] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CRTX_Extras] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CRTX_Extras] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CRTX_Extras] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CRTX_Extras] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CRTX_Extras] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CRTX_Extras] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CRTX_Extras] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CRTX_Extras] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CRTX_Extras] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CRTX_Extras] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CRTX_Extras] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CRTX_Extras] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CRTX_Extras] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CRTX_Extras] SET RECOVERY FULL 
GO

ALTER DATABASE [CRTX_Extras] SET  MULTI_USER 
GO

ALTER DATABASE [CRTX_Extras] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CRTX_Extras] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CRTX_Extras] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CRTX_Extras] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CRTX_Extras] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CRTX_Extras] SET QUERY_STORE = OFF
GO

USE [CRTX_Extras]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [CRTX_Extras] SET  READ_WRITE 
GO

/****** Object:  Table [dbo].[cortex_MD_menu]    Script Date: 10/16/2020 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[cortex_MD_menu](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[menu_text] [nvarchar](32) NULL,
	[icon] [nvarchar](50) NULL,
	[usergroups] [nvarchar](max) NULL,
	[menu_order] [int] NULL,
	[icon_html] [nvarchar](100) NULL,
 CONSTRAINT [PK_cortex_MD_menu] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

/****** Object:  Table [dbo].[cortex_MD_widget]    Script Date: 10/16/2020 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[cortex_MD_widget](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[menu_id] [int] NULL,
	[title] [nvarchar](50) NULL,
	[description] [nvarchar](150) NULL,
	[icon] [nvarchar](50) NULL,
	[icon_colour] [nvarchar](50) NULL,
	[button_text] [nvarchar](50) NULL,
	[background] [nvarchar](50) NULL,
	[trigger_option] [nvarchar](50) NULL,
	[trigger_target] [nvarchar](2000) NULL,
	[width] [int] NULL,
	[output_html] [nvarchar](max) NULL,
	[widget_order] [int] NULL,
 CONSTRAINT [PK_cortex_MD_widget] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

ALTER TABLE [dbo].[cortex_MD_widget]  WITH CHECK ADD  CONSTRAINT [FK_cortex_MD_widget_cortex_MD_menu] FOREIGN KEY([menu_id])
REFERENCES [dbo].[cortex_MD_menu] ([id])
GO

ALTER TABLE [dbo].[cortex_MD_widget] CHECK CONSTRAINT [FK_cortex_MD_widget_cortex_MD_menu]
GO


